### ISSUE TITLE
is training section duplicated?

### ISSUE THREAD

**Issue by walidshaari** [magnologan/awesome-k8s-security#3]
There are two training sections? I would like to add some of the training that is available out there from acloud.guru, Pluralsight, LinkedIn learning, which section should I put it under?

**Comment by magnologan** [comment]
Hi @walidshaari, so, yes, the 1st training section is for general trainings around Kubernetes in general, the 2nd section is for specific trainings related to K8s security, make sense? So if the trainings are more generic around how to use k8s and how it works, then please put them in the 1st section, otherwise if they are security related, please add them into the 2nd section. I hope that helps! Thanks for contributing!
